"""
Export analysis results to JSON or Markdown.
"""

from __future__ import annotations

import json
from pathlib import Path


def export_json(data: dict, path: Path) -> None:
    path.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")


def export_markdown(data: dict, path: Path) -> None:
    repo = data["repo"]
    bus = data["bus_factor"]
    issues = data["issue_velocity"]
    commits = data["commit_activity"]
    releases = data["releases"]
    score = data["health_score"]
    notes = data["health_notes"]

    score_emoji = "🟢" if score >= 80 else ("🟡" if score >= 60 else ("🟠" if score >= 40 else "🔴"))

    lines = [
        f"# repo-pulse Report: `{repo['full_name']}`",
        "",
        f"> {repo['description']}",
        "",
        f"**URL:** {repo['url']}  ",
        f"**Language:** {repo['language']}  ",
        f"**License:** {repo['license']}  ",
        f"**Created:** {repo['created_at']}",
        "",
        "---",
        "",
        f"## {score_emoji} Health Score: {score}/100",
        "",
    ]

    if notes:
        lines += ["### ⚡ Warnings", ""]
        for n in notes:
            lines.append(f"- {n}")
        lines.append("")

    lines += [
        "---",
        "",
        "## 📊 Community Signals",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| ⭐ Stars | {repo['stars']:,} |",
        f"| 🍴 Forks | {repo['forks']:,} |",
        f"| 👁 Watchers | {repo['watchers']:,} |",
        f"| 🐛 Open Issues | {repo['open_issues']:,} |",
        f"| 🕐 Days Since Last Commit | {repo['days_since_last_commit']} |",
        "",
        "---",
        "",
        "## 👥 Bus Factor",
        "",
        f"**Bus Factor:** {bus['bus_factor']} ({bus['risk'].upper()} risk)",
        "",
        "| Contributor | Commits | Share |",
        "|-------------|---------|-------|",
    ]

    for c in bus["top_contributors"]:
        lines.append(f"| @{c['login']} | {c['contributions']} | {c['pct']}% |")

    lines += [
        "",
        "---",
        "",
        "## 🐛 Issue Velocity",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Open Issues | {issues['open']} |",
        f"| Closed Issues | {issues['closed']} |",
        f"| Closure Rate | {issues['closure_rate_pct']}% |",
        f"| Status | {issues['health'].upper()} |",
    ]

    if issues["avg_close_days"] is not None:
        lines.append(f"| Avg Days to Close | {issues['avg_close_days']} |")

    lines += [
        "",
        "---",
        "",
        "## 📈 Commit Activity",
        "",
        f"- **Commits sampled:** {commits['total_sampled']}",
        f"- **Avg commits/month:** {commits['avg_commits_per_month']}",
        f"- **Active authors (sample):** {commits['active_authors']}",
        "",
        "---",
        "",
        "## 🚀 Releases",
        "",
        f"- **Total releases:** {releases['total']}",
    ]

    if releases["latest"]:
        lines.append(f"- **Latest:** {releases['latest']} ({releases['latest_date']})")

    lines += [
        "",
        "---",
        "",
        "*Generated by [repo-pulse](https://github.com/yourusername/repo-pulse)*",
    ]

    path.write_text("\n".join(lines), encoding="utf-8")
